### PR TITLE
Python 3 version

### PR DESCRIPTION
**Pull request by c0d3ma5t3r**
Added a py3 version with some 3.1x methods with it

### CODE REVIEW

**Comment by setherith** [comment]
You beat me to it! I just finished watching John Hammond on YT and thought: "I can convert that to Python 3..."!

**Comment by c0d3ma5t3r** [comment]
Yeah that is what I ended up thinking too! I don't think we will get a successful pull request since it has not been touched in 6 years. But at least now there is one out there people can use.

**Comment by w3ich3rt** [comment]
I just want to start the same thing... you guys are awesome!

**Review by JassonCordones — COMMENTED** [review]
Could use some comments but It would be cool this is merged even as it is.

**Review by Th3S3cr3tAg3nt — APPROVED** [review]
This is much more pythonic code than my original.

**Comment by JassonCordones** [comment]
I didn't even remember I made this comment, lol

**Pull request merged**
